// SiYuan - Refactor your thinking
// Copyright (c) 2020-present, b3log.org
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package thumbnail

import (
	"bytes"
	"crypto/md5"
	"encoding/hex"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"sync"

	"github.com/88250/gulu"
	"github.com/siyuan-note/logging"
	"github.com/siyuan-note/siyuan/kernel/util"
	"golang.org/x/sync/singleflight"
)

var (
	// ErrProviderFailed 表示所有 Provider 都无法生成缩略图
	ErrProviderFailed = errors.New("thumbnail generation failed")
	// ErrRefused 表示 Provider 拒绝处理该文件
	ErrRefused = errors.New("provider refused to handle")
	// ErrFileNotFound 表示文件不存在
	ErrFileNotFound = errors.New("file not found")
)

// Service 定义缩略图服务接口
type Service interface {
	// Get 返回指定文件的缩略图数据
	// filePath: 绝对路径
	// maxSize: 最大边长（宽或高的最大值）
	Get(filePath string, maxSize int) (data []byte, contentType string, err error)

	// GetWithSize 返回指定尺寸的缩略图
	// filePath: 绝对路径
	// width, height: 目标尺寸（保持宽高比填充到此范围内）
	GetWithSize(filePath string, width, height int) (data []byte, contentType string, err error)
}

// Provider 定义缩略图生成器接口
type Provider interface {
	// Name 返回 Provider 名称
	Name() string
	// CanHandle 检查是否能处理该文件
	CanHandle(filePath string) bool
	// Generate 生成缩略图
	// width, height: 目标尺寸范围
	Generate(filePath string, width, height int) (data []byte, err error)
	// Priority 返回优先级 (越小越高)
	Priority() int
}

// Manager 实现 Service 接口，管理多个 Provider
type Manager struct {
	providers []Provider

	// Cache config
	cacheDir string
	mutex    sync.RWMutex

	// SingleFlight 防止同时生成相同的缩略图
	sfGroup singleflight.Group
}

var instance *Manager
var once sync.Once

// NewInstance 创建或获取单例
func NewInstance() *Manager {
	once.Do(func() {
		instance = &Manager{
			providers: make([]Provider, 0),
			cacheDir:  filepath.Join(util.TempDir, "thumbnails", "s-forge"),
		}

		if err := os.MkdirAll(instance.cacheDir, 0755); err != nil {
			logging.LogErrorf("failed to create thumbnail cache dir: %v", err)
		}

		instance.registerProviders()
	})
	return instance
}

// registerProviders 注册所有可用的 Provider
// 注册顺序决定优先级：先注册的会先尝试
func (m *Manager) registerProviders() {
	// 1. 专用格式 Provider 必须先于 Windows 泛化 Provider，保持参考实现的格式语义。
	for _, provider := range []Provider{NewSVGProvider(), NewD5MProvider()} {
		m.providers = append(m.providers, provider)
		logging.LogInfof("registered thumbnail provider: %s", provider.Name())
	}

	// 2. Windows Provider (Highest Priority on Windows)
	//    使用 Windows Shell API，支持系统能预览的所有文件
	if p := NewWindowsProvider(); p != nil {
		m.providers = append(m.providers, p)
		logging.LogInfof("registered thumbnail provider: %s", p.Name())
	}

	// 3. Go Imaging Provider (图片通用处理)
	//    纯 Go 实现，支持常见图片格式
	m.providers = append(m.providers, NewGoImagingProvider())
	logging.LogInfof("registered thumbnail provider: GoImaging")
}

// Get 获取缩略图（使用最大边长）
func (m *Manager) Get(filePath string, maxSize int) (data []byte, contentType string, err error) {
	return m.GetWithSize(filePath, maxSize, maxSize)
}

// GetWithSize 获取指定尺寸的缩略图
func (m *Manager) GetWithSize(filePath string, width, height int) (data []byte, contentType string, err error) {
	// 参数校验
	if width <= 0 {
		width = 256
	}
	if height <= 0 {
		height = 256
	}
	if width > 2048 {
		width = 2048
	}
	if height > 2048 {
		height = 2048
	}

	// 检查文件是否存在
	if !gulu.File.IsExist(filePath) {
		return nil, "", ErrFileNotFound
	}

	// 使用 singleflight 防止并发重复生成
	cacheKey := m.getCacheKey(filePath, width, height)
	if cacheKey == "" {
		return nil, "", ErrFileNotFound
	}

	result, err, _ := m.sfGroup.Do(cacheKey, func() (interface{}, error) {
		// 1. 检查缓存
		if cachedData, ok := m.checkCache(cacheKey); ok {
			return cachedData, nil
		}

		// 2. 生成缩略图
		data, genErr := m.generate(filePath, width, height)
		if genErr != nil {
			return nil, genErr
		}

		// 3. 写入缓存
		m.writeCache(cacheKey, data)

		return data, nil
	})

	if err != nil {
		return nil, "", err
	}

	data = result.([]byte)
	return data, detectContentType(data), nil
}

// generate 尝试使用各个 Provider 生成缩略图
func (m *Manager) generate(filePath string, width, height int) ([]byte, error) {
	m.mutex.RLock()
	defer m.mutex.RUnlock()

	var lastErr error
	for _, p := range m.providers {
		if !p.CanHandle(filePath) {
			continue
		}

		data, err := p.Generate(filePath, width, height)
		if err == nil && len(data) > 0 {
			logging.LogInfof("thumbnail generated by [%s] for [%s]", p.Name(), filePath)
			return data, nil
		}
		lastErr = err
		logging.LogInfof("provider [%s] failed to generate thumbnail for [%s]: %v", p.Name(), filePath, err)
	}

	if lastErr != nil {
		return nil, lastErr
	}
	return nil, ErrProviderFailed
}

// getCacheKey 生成缓存键
// 格式: Hash(AbsPath)_MTime_WxH.jpg
func (m *Manager) getCacheKey(filePath string, width, height int) string {
	info, err := os.Stat(filePath)
	if err != nil {
		return ""
	}

	h := md5.Sum([]byte(filePath))
	hash := hex.EncodeToString(h[:])
	mtime := strconv.FormatInt(info.ModTime().Unix(), 10)
	return fmt.Sprintf("%s_%s_%dx%d", hash, mtime, width, height)
}

// checkCache 检查缓存是否存在
func (m *Manager) checkCache(cacheKey string) ([]byte, bool) {
	if cacheKey == "" {
		return nil, false
	}

	// 尝试所有可能的后缀
	for _, ext := range []string{".png", ".jpg", ".svg", ".bin"} {
		cachePath := filepath.Join(m.cacheDir, cacheKey+ext)
		if gulu.File.IsExist(cachePath) {
			data, err := os.ReadFile(cachePath)
			if err == nil {
				return data, true
			}
		}
	}
	return nil, false
}

// writeCache 写入缓存
func (m *Manager) writeCache(cacheKey string, data []byte) {
	if cacheKey == "" || len(data) == 0 {
		return
	}

	// 根据内容类型确定后缀
	ext := ".bin"
	if len(data) > 8 {
		// PNG: 89 50 4E 47 0D 0A 1A 0A
		if data[0] == 0x89 && data[1] == 0x50 && data[2] == 0x4E && data[3] == 0x47 {
			ext = ".png"
		} else if data[0] == 0xFF && data[1] == 0xD8 {
			// JPEG: FF D8
			ext = ".jpg"
		} else if string(data[:5]) == "<?xml" || string(data[:4]) == "<svg" {
			ext = ".svg"
		}
	}

	// 异步写入文件系统
	go func() {
		cachePath := filepath.Join(m.cacheDir, cacheKey+ext)
		tmpPath := cachePath + ".tmp"
		if err := os.WriteFile(tmpPath, data, 0644); err == nil {
			os.Rename(tmpPath, cachePath)
		}
	}()
}

// ClearCache 清除指定文件的缓存
func (m *Manager) ClearCache(filePath string, width, height int) error {
	cacheKey := m.getCacheKey(filePath, width, height)
	if cacheKey == "" {
		return nil
	}

	// 删除所有可能的缓存文件
	for _, ext := range []string{".png", ".jpg", ".svg", ".bin"} {
		cachePath := filepath.Join(m.cacheDir, cacheKey+ext)
		os.Remove(cachePath)
	}
	return nil
}

// ClearAllCache 清除所有缩略图缓存
func (m *Manager) ClearAllCache() error {
	m.mutex.Lock()
	defer m.mutex.Unlock()

	if err := os.RemoveAll(m.cacheDir); err != nil {
		return err
	}
	return os.MkdirAll(m.cacheDir, 0755)
}

// Refresh 强制刷新缓存（重新生成缩略图并更新缓存）
func (m *Manager) Refresh(filePath string, width, height int) (data []byte, contentType string, err error) {
	// 参数校验
	if width <= 0 {
		width = 256
	}
	if height <= 0 {
		height = 256
	}
	if width > 2048 {
		width = 2048
	}
	if height > 2048 {
		height = 2048
	}

	// 检查文件是否存在
	if !gulu.File.IsExist(filePath) {
		return nil, "", ErrFileNotFound
	}

	// 直接生成，不检查缓存
	data, err = m.generate(filePath, width, height)
	if err != nil {
		return nil, "", err
	}

	// 写入缓存（更新缓存）
	cacheKey := m.getCacheKey(filePath, width, height)
	m.writeCache(cacheKey, data)

	contentType = detectContentType(data)

	return data, contentType, nil
}

func detectContentType(data []byte) string {
	trimmed := bytes.TrimSpace(data)
	switch {
	case len(data) >= 8 && bytes.Equal(data[:8], []byte{0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a}):
		return "image/png"
	case len(data) >= 2 && data[0] == 0xff && data[1] == 0xd8:
		return "image/jpeg"
	case bytes.HasPrefix(trimmed, []byte("<?xml")) || bytes.HasPrefix(trimmed, []byte("<svg")):
		return "image/svg+xml"
	default:
		return http.DetectContentType(data)
	}
}
