/**
 * 块查询相关 API 定义
 * 
 * 包含: getBlockInfo, getBlockDOM, getChildBlocks, getBlockBreadcrumb 等
 */
import { z } from 'zod';
import type { Api定义 } from '../../client/types';
import { 创建响应Schema } from '../types';
import { 块信息Schema, 子块信息Schema, 面包屑项Schema, 文档信息Schema, 树统计Schema, 字数统计Schema } from './schemas';

export const queryApiDefs = [
    // ========== 获取块信息 ==========
    {
        method: 'POST',
        endpoint: '/api/block/getBlockInfo',
        en: 'getBlockInfo',
        zh_cn: '获取块信息',
        description: '获取指定块ID的详细信息。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('要获取信息的块 ID'),
        }),
        zodResponseSchema: 创建响应Schema(块信息Schema),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getBlockDOM',
        en: 'getBlockDOM',
        zh_cn: '获取块DOM',
        description: '获取指定块ID的DOM表示（HTML字符串）。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('要获取 DOM 的块 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            id: z.string().describe('块 ID'),
            dom: z.string().describe('块的 DOM 内容'),
        })),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getBlockDOMs',
        en: 'getBlockDOMs',
        zh_cn: '批量获取块DOM',
        description: '批量获取指定块ID列表的DOM表示。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            ids: z.array(z.string()).describe('要获取 DOM 的块 ID 数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.record(z.string(), z.string())),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getBlockDOMWithEmbed',
        en: 'getBlockDOMWithEmbed',
        zh_cn: '获取块DOM（含嵌入）',
        description: '获取指定块ID的DOM表示，包含嵌入块的内容。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('要获取 DOM 的块 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            id: z.string().describe('块 ID'),
            dom: z.string().describe('块的 DOM 内容（含嵌入）'),
        })),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getBlockDOMsWithEmbed',
        en: 'getBlockDOMsWithEmbed',
        zh_cn: '批量获取块DOM（含嵌入）',
        description: '批量获取指定块ID列表的DOM表示，包含嵌入块的内容。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            ids: z.array(z.string()).describe('要获取 DOM 的块 ID 数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.record(z.string(), z.string())),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getBlockKramdown',
        en: 'getBlockKramdown',
        zh_cn: '获取块Kramdown源码',
        description: '获取指定块ID的Kramdown源码表示。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('要获取 Kramdown 源码的块 ID'),
            mode: z.enum(['md', 'textmark']).optional().describe('获取模式'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            id: z.string().describe('块 ID'),
            kramdown: z.string().describe('块的 Kramdown 源码'),
        })),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getChildBlocks',
        en: 'getChildBlocks',
        zh_cn: '获取子块基本信息',
        description: '获取指定块ID的所有直接子块的基本信息列表。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('父块的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.array(子块信息Schema)),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getTailChildBlocks',
        en: 'getTailChildBlocks',
        zh_cn: '获取块的尾部若干子块',
        description: '获取指定块ID的尾部指定数量的直接子块。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('父块的 ID'),
            n: z.number().int().optional().describe('要获取的尾部子块数量，默认为 7'),
        }),
        zodResponseSchema: 创建响应Schema(z.array(子块信息Schema)),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getBlockBreadcrumb',
        en: 'getBlockBreadcrumb',
        zh_cn: '获取块面包屑',
        description: '获取指定块ID到其根块的面包屑路径。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('目标块的 ID'),
            excludeTypes: z.array(z.string()).optional().describe('需要排除的块类型数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.array(面包屑项Schema)),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getBlockIndex',
        en: 'getBlockIndex',
        zh_cn: '获取块在父级中的位置',
        description: '获取指定块ID在其父级块的子块列表中的位置索引。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('要获取索引的块 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.number()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getBlocksIndexes',
        en: 'getBlocksIndexes',
        zh_cn: '批量获取块在父级中的位置',
        description: '批量获取指定块ID列表各自在其父级块的子块列表中的位置索引。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            ids: z.array(z.string()).describe('要获取索引的块 ID 数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.record(z.string(), z.number())),
        lastVerified: '2025-12-28',
    },

    // ========== 字数统计 ==========
    {
        method: 'POST',
        endpoint: '/api/block/getTreeStat',
        en: 'getTreeStat',
        zh_cn: '获取块树统计信息',
        description: '获取指定块ID的树结构统计信息。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('目标块的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            reqId: z.string().optional().describe('如果请求中提供了 reqId'),
            stat: 树统计Schema.describe('树统计信息'),
        })),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getBlocksWordCount',
        en: 'getBlocksWordCount',
        zh_cn: '获取多块字数统计',
        description: '获取指定块ID列表的总字数、字符数和链接数统计信息。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            ids: z.array(z.string()).describe('要统计字数的块 ID 数组'),
            reqId: z.string().optional().describe('可选的请求 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            reqId: z.string().optional().describe('如果请求中提供了 reqId'),
            stat: 字数统计Schema.describe('字数统计结果'),
        })),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getContentWordCount',
        en: 'getContentWordCount',
        zh_cn: '获取内容字数统计',
        description: '获取给定内容字符串的字数统计信息。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            content: z.string().describe('要统计字数的文本内容'),
            reqId: z.string().optional().describe('可选的请求 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            reqId: z.string().optional().describe('如果请求中提供了 reqId'),
            stat: 字数统计Schema.describe('字数统计结果'),
        })),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getRecentUpdatedBlocks',
        en: 'getRecentUpdatedBlocks',
        zh_cn: '获取最近更新的块列表',
        description: '获取最近更新的块列表，按更新时间倒序排列。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.array(z.object({
            id: z.string().describe('块 ID'),
            box: z.string().describe('笔记本 ID'),
            path: z.string().describe('块所在文档的路径'),
            hPath: z.string().describe('块所在文档的人类可读路径'),
            name: z.string().describe('块的名称/内容预览'),
            bookmark: z.string().describe('块的书签内容'),
            memo: z.string().describe('块的备注内容'),
            alias: z.string().describe('块的别名'),
            type: z.string().describe('块类型'),
            updated: z.string().describe('块更新时间'),
        }))),
        lastVerified: '2025-12-28',
    },

    // ========== 文档信息 ==========
    {
        method: 'POST',
        endpoint: '/api/block/getDocInfo',
        en: 'getDocInfo',
        zh_cn: '获取文档信息',
        description: '获取指定文档块ID的信息。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('目标文档块的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(文档信息Schema),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getDocsInfo',
        en: 'getDocsInfo',
        zh_cn: '批量获取多个文档信息',
        description: '批量获取多个文档块ID的信息。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            ids: z.array(z.string()).describe('包含多个文档块 ID 的数组'),
            refCount: z.boolean().optional().describe('是否查询引用计数'),
            av: z.boolean().optional().describe('是否查询属性视图信息'),
        }),
        zodResponseSchema: 创建响应Schema(z.array(z.object({
            id: z.string().describe('文档块 ID'),
            box: z.string().describe('笔记本 ID'),
            path: z.string().describe('文档的存储路径'),
            title: z.string().describe('文档标题'),
            icon: z.string().describe('文档图标'),
            iconURL: z.string().describe('文档图标的 URL'),
            isTemplate: z.boolean().describe('该文档是否为模板'),
            updated: z.string().describe('文档更新时间'),
        }))),
        lastVerified: '2025-12-28',
    },

    // ========== 检查块状态 ==========
    {
        method: 'POST',
        endpoint: '/api/block/checkBlockExist',
        en: 'checkBlockExist',
        zh_cn: '检查块是否存在',
        description: '检查指定的块ID是否存在。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('要检查的块 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.boolean()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getUnfoldedParentID',
        en: 'getUnfoldedParentID',
        zh_cn: '获取块的最近展开的父块ID',
        description: '向上查找指定块ID的父块链，返回最近的一个已展开的父块ID。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('起始块的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            parentID: z.string().describe('最近展开的父块ID'),
        })),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/checkBlockFold',
        en: 'checkBlockFold',
        zh_cn: '检查块是否折叠',
        description: '检查指定的块ID是否已折叠。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('要检查的块 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            isFolded: z.boolean().describe('块是否已折叠'),
            isRoot: z.boolean().describe('块是否为根块'),
        })),
        lastVerified: '2025-12-28',
    },

    // ========== 其他查询 ==========
    {
        method: 'POST',
        endpoint: '/api/block/getBlockSiblingID',
        en: 'getBlockSiblingID',
        zh_cn: '获取块的同级和父级ID',
        description: '获取指定块ID的父块ID、上一个同级块ID和下一个同级块ID。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('目标块的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            parent: z.string().describe('父块 ID'),
            previous: z.string().describe('上一个同级块 ID'),
            next: z.string().describe('下一个同级块 ID'),
        })),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getBlockTreeInfos',
        en: 'getBlockTreeInfos',
        zh_cn: '获取多个块的树信息',
        description: '批量获取指定块ID列表对应的块树信息。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            ids: z.array(z.string()).describe('要获取块树信息的块 ID 数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.array(z.any())),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/block/getBlockRelevantIDs',
        en: 'getBlockRelevantIDs',
        zh_cn: '获取块相关ID',
        description: '获取与指定块相关的ID列表。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('目标块的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            parentID: z.string().describe('父块 ID'),
            previousID: z.string().describe('上一个同级块 ID'),
            nextID: z.string().describe('下一个同级块 ID'),
        })),
        lastVerified: '2025-12-28',
    },
] as const satisfies readonly Api定义[];
