const fs = require('fs');
const path = require('path');
const { z } = require('zod');
const { pathToFileURL } = require('url');

// API定义目录和输出文件路径
const API_DEFS_DIR = path.join(__dirname, 'packages','apiDefs');
const OUTPUT_FILE = path.join(__dirname,'packages', 'kernelApiClient.ts');

// 生成的文件头部注释
const GENERATED_BANNER = `// Generated by generateSingleFileClient.ts, do not edit manually.
// Timestamp: ${new Date().toISOString()}
// Based on API definitions from: ${API_DEFS_DIR}
`;

// API定义接口
// 注意：这是在生成的TypeScript文件中使用的接口，这里只是作为字符串模板

// 检查对象是否为Zod原始形状
const isZodRawShape = (obj) => {
    if (typeof obj !== "object" || obj === null) return false;
    // Allow empty object {} to be handled by later logic, not strictly a "raw shape with Zod types"
    if (Object.keys(obj).length === 0 && !obj._def) return false; 
    return Object.values(obj).some(v => v?._def?.typeName);
};

// 获取Zod基本类型名称
function getZodPrimitiveTypeName(zodType) {
    if (!zodType || !zodType._def || !zodType._def.typeName) return 'any';
    const typeName = zodType._def.typeName;
    switch (typeName) {
        case 'ZodString': return 'string';
        case 'ZodNumber': return 'number';
        case 'ZodBoolean': return 'boolean';
        case 'ZodDate': return 'Date';
        case 'ZodNull': return 'null';
        case 'ZodVoid': return 'void';
        case 'ZodAny': return 'any';
        case 'ZodUnknown': return 'unknown';
        case 'ZodNever': return 'never';
        case 'ZodBigInt': return 'bigint';
        case 'ZodSymbol': return 'symbol';
        case 'ZodUndefined': return 'undefined';
        default: return 'any';
    }
}

/**
 * 递归解析Zod类型并生成其TypeScript类型表示
 * @param zodType - Zod类型实例
 * @param linePrefix - 每个生成的TypeScript行的字符串前缀，用于嵌套属性
 * @returns 包含类型、描述和详细信息的对象
 */
function parseZodTypeForTs(zodType, linePrefix) {
    if (!zodType || !zodType._def) {
        return { type: 'any', description: '', details: [] };
    }

    const typeName = zodType._def.typeName;
    let description = zodType.description || '';
    let tsType = getZodPrimitiveTypeName(zodType);
    let details = [];

    switch (typeName) {
        case 'ZodObject':
            tsType = 'object';
            const shape = zodType._def.shape();
            const propertyLinePrefix = linePrefix + '  '; // 进一步缩进属性
            for (const key in shape) {
                const propTypeInstance = shape[key];
                const propTs = parseZodTypeForTs(propTypeInstance, propertyLinePrefix);
                let propFinalDescription = propTs.description || key;
                
                details.push(`${propertyLinePrefix}${key}: ${propTs.type};`);
                if (propTs.details.length > 0) {
                    details.push(...propTs.details); 
                }
            }
            break;
        case 'ZodArray':
            const elementType = zodType._def.type;
            const elementTs = parseZodTypeForTs(elementType, linePrefix); 
            tsType = `${elementTs.type}[]`;
            if (elementType._def?.typeName === 'ZodObject' && elementTs.details.length > 0) {
                 // details.push(...elementTs.details.map(d => `${linePrefix}(element)${d.substring(linePrefix.length)}`));
            }
            break;
        case 'ZodOptional':
        case 'ZodNullable':
            const innerTypeOptionalNullable = zodType._def.innerType;
            const innerTsON = parseZodTypeForTs(innerTypeOptionalNullable, linePrefix);
            tsType = innerTsON.type + (typeName === 'ZodOptional' ? ' | undefined' : ' | null');
            description = description || innerTsON.description; 
            details = innerTsON.details; 
            break;
        case 'ZodUnion':
            const options = zodType._def.options;
            tsType = options.map(opt => parseZodTypeForTs(opt, linePrefix).type).join(' | ');
            break;
        case 'ZodRecord':
            const keyType = zodType._def.keyType ? parseZodTypeForTs(zodType._def.keyType, linePrefix).type : 'string';
            const valueTypeInfo = parseZodTypeForTs(zodType._def.valueType, linePrefix);
            tsType = `Record<${keyType}, ${valueTypeInfo.type}>`;
            description = description || valueTypeInfo.description; 
            details = valueTypeInfo.details; 
            break;
        case 'ZodLiteral':
            const literalValue = zodType._def.value;
            tsType = typeof literalValue === 'string' ? `"${literalValue.replace(/"/g, '\\"')}"` : String(literalValue);
            break;
        case 'ZodEnum':
            tsType = zodType._def.values.map(v => typeof v === 'string' ? `"${v.replace(/"/g, '\\"')}"` : String(v)).join(' | ');
            break;
        case 'ZodLazy': 
            tsType = 'object'; 
            description = description || 'Lazily loaded type, structure defined elsewhere.';
            break;
    }
    return { type: tsType, description, details };
}

/**
 * 从模式生成参数或返回类型的TypeScript行
 * @param apiDefSchemaFn - apiDef中的函数（例如zodRequestSchema）
 * @param zInstance - Zod实例
 * @param baseTsLinePrefix - 每个TypeScript行的前缀
 * @param isReturn - 是否为返回类型生成，否则为参数类型
 * @returns TypeScript行数组
 */
function generateTsLinesFromSchema(apiDefSchemaFn, zInstance, baseTsLinePrefix, isReturn = false) {
    if (!apiDefSchemaFn) return [];

    let schemaOrShape;
    try {
        schemaOrShape = apiDefSchemaFn(zInstance);
    } catch (e) {
        return [];
    }

    const lines = [];

    if (!schemaOrShape || (typeof schemaOrShape === 'object' && !schemaOrShape._def && Object.keys(schemaOrShape).length === 0)) {
        const desc = (schemaOrShape && typeof schemaOrShape === 'object' && schemaOrShape.description) ? schemaOrShape.description : (isReturn ? 'The response from the server.' : 'Request payload');
        const type = isReturn ? 'Promise<object>' : 'object';
        const paramOrReturn = isReturn ? `: Promise<${type}>` : `data: ${type}`;
        lines.push(`${baseTsLinePrefix}${paramOrReturn}`);
        return lines;
    }
    
    if (isZodRawShape(schemaOrShape)) {
        const overallDescription = schemaOrShape.description || (isReturn ? 'The response from the server.' : 'Request payload');
        const baseType = 'object';
        const promiseWrappedType = isReturn ? `Promise<${baseType}>` : baseType;
        
        const mainLine = isReturn ? `: Promise<${baseType}>` : `data: ${baseType}`;
        lines.push(`${baseTsLinePrefix}${mainLine}`);

        const propertyLinePrefix = baseTsLinePrefix + '  '; 
        for (const key in schemaOrShape) {
            if (key === 'description') continue; 

            const propZodType = schemaOrShape[key];
            if (propZodType && propZodType._def) { 
                const propTs = parseZodTypeForTs(propZodType, propertyLinePrefix); 
                let propFinalDescription = propTs.description || key;

                lines.push(`${propertyLinePrefix}${key}: ${propTs.type};`);
                if (propTs.details.length > 0) {
                    lines.push(...propTs.details);
                }
            } else {
                lines.push(`${propertyLinePrefix}${key}: any;`);
            }
        }
    } else if (schemaOrShape && schemaOrShape._def) { 
        const parsedResult = parseZodTypeForTs(schemaOrShape, baseTsLinePrefix);
        if (isReturn) {
            let returnType = parsedResult.type;
            if (returnType === 'void') { 
                returnType = 'Promise<void>';
            } else {
                returnType = `Promise<${returnType}>`;
            }
            lines.push(`${baseTsLinePrefix}: ${returnType}`);
        } else { 
            lines.push(`${baseTsLinePrefix}data: ${parsedResult.type}`);
        }

        if (parsedResult.details.length > 0 && parsedResult.type === 'object') {
            lines.push(...parsedResult.details);
        }
    } else {
        const type = isReturn ? 'Promise<any>' : 'any';
        const paramOrReturn = isReturn ? `: Promise<${type}>` : `data: ${type}`;
        lines.push(`${baseTsLinePrefix}${paramOrReturn}`);
    }
    return lines;
}

async function getAllApiDefs() {
    const allDefs = [];
    const files = fs.readdirSync(API_DEFS_DIR);
    for (const file of files) {
        if (file.endsWith('.js')) {
            const groupName = file.replace('.js', '');
            try {
                const modulePath = path.join(API_DEFS_DIR, file);
                const defsModule = await import(pathToFileURL(modulePath).href);
                const apiDefsArray = defsModule[`${groupName}ApiDefs`];
                if (Array.isArray(apiDefsArray)) {
                    apiDefsArray.forEach(def => {
                        allDefs.push({ ...def, groupName });
                    });
                } else {
                    console.warn(`Skipping ${file}: expected ${groupName}ApiDefs to be an array.`);
                }
            } catch (error) {
                console.error(`Error loading API definitions from ${file}:`, error);
            }
        }
    }
    return allDefs;
}

function generateMethodTsDoc(apiDef, hasDataParam) {
    const baseIndentStr = '  '; 
    const tsDocLinePrefix = `${baseIndentStr} * `;
    
    let tsDocLines = [`${baseIndentStr}/**`];
    tsDocLines.push(`${tsDocLinePrefix}${apiDef.zh_cn || apiDef.en}`);
    if (apiDef.deprecated) {
        tsDocLines.push(`${tsDocLinePrefix}@deprecated ${typeof apiDef.deprecated === 'string' ? apiDef.deprecated : ''}`);
    }
    tsDocLines.push(`${tsDocLinePrefix}Endpoint: \`${apiDef.method} ${apiDef.endpoint}\``);
    if (apiDef.needAuth) {
        tsDocLines.push(`${tsDocLinePrefix}Requires authentication.`);
    }

    if (hasDataParam && apiDef.zodRequestSchema) {
        const requestLines = generateTsLinesFromSchema(apiDef.zodRequestSchema, z, tsDocLinePrefix, false);
        tsDocLines.push(...requestLines);
    } else if (hasDataParam) { 
        tsDocLines.push(`${tsDocLinePrefix}@param data Request payload`);
    }

    if (apiDef.zodResponseSchema) {
        const responseLines = generateTsLinesFromSchema(apiDef.zodResponseSchema, z, tsDocLinePrefix, true);
        tsDocLines.push(...responseLines);
    } else {
        tsDocLines.push(`${tsDocLinePrefix}@returns The response data from the server.`);
    }

    tsDocLines.push(`${tsDocLinePrefix}@throws If the request fails or the server returns an error.`);
    tsDocLines.push(`${baseIndentStr} */`);
    // 在连接最终字符串的行时，使用 \n，它是模板字符串或常规字符串中的字面换行符。
    // 如果此字符串随后写入文件，\n 将正确成为换行符。
    return tsDocLines.join('\n') + '\n'; 
}

function zodToTsType(zodType) {
    if (!zodType || !zodType._def) return 'any';
    const typeName = zodType._def.typeName;

    switch (typeName) {
        case 'ZodString': return 'string';
        case 'ZodNumber': return 'number';
        case 'ZodBoolean': return 'boolean';
        case 'ZodDate': return 'Date';
        case 'ZodNull': return 'null';
        case 'ZodVoid': return 'void';
        case 'ZodAny': return 'any';
        case 'ZodUnknown': return 'unknown';
        case 'ZodNever': return 'never';
        case 'ZodBigInt': return 'bigint';
        case 'ZodSymbol': return 'symbol';
        case 'ZodUndefined': return 'undefined';
        
        case 'ZodObject':
            const shape = zodType._def.shape();
            const properties = Object.keys(shape).map(key => {
                const propTypeInstance = shape[key];
                let isOptional = false;
                let innerType = propTypeInstance;

                if (propTypeInstance._def.typeName === 'ZodOptional') {
                    isOptional = true;
                    innerType = propTypeInstance._def.innerType;
                }
                
                const propTypeString = zodToTsType(innerType);
                const finalKey = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key) ? key : `"${key}"`;
                return `${finalKey}${isOptional ? '?' : ''}: ${propTypeString}`;
            });
            if (properties.length === 0) return '{}';
            return `{ ${properties.join('; ')} }`;

        case 'ZodArray':
            return `${zodToTsType(zodType._def.type)}[]`;

        case 'ZodOptional':
            return `${zodToTsType(zodType._def.innerType)} | undefined`;
        case 'ZodNullable':
            return `${zodToTsType(zodType._def.innerType)} | null`;

        case 'ZodUnion':
            return zodType._def.options.map(opt => zodToTsType(opt)).join(' | ');

        case 'ZodRecord':
            const keyType = zodType._def.keyType ? zodToTsType(zodType._def.keyType) : 'string';
            const valueType = zodToTsType(zodType._def.valueType);
            return `Record<${keyType}, ${valueType}>`;

        case 'ZodLiteral':
            const literalValue = zodType._def.value;
            return typeof literalValue === 'string' ? `"${literalValue.replace(/"/g, '\\"')}"` : String(literalValue);

        case 'ZodEnum':
            return zodType._def.values.map(v => typeof v === 'string' ? `"${v.replace(/"/g, '\\"')}"` : String(v)).join(' | ');
        
        case 'ZodLazy':
            return 'any';

        default: return 'any';
    }
}

async function generateKernelApiClient() {
    const apiDefs = await getAllApiDefs();
    let classBody = '';
    let methodCount = 0; // 初始化计数器

    // 添加类型定义
    classBody += `${GENERATED_BANNER}

interface KernelApiClientOptions {
  baseUrl?: string;
  apiToken?: string;
  customFetch?: (input: RequestInfo, init?: RequestInit) => Promise<Response>;
}

`;

    classBody += `
class KernelApiClient {
   baseUrl: string;
   apiToken: string;
  private customFetch: (input: RequestInfo, init?: RequestInit) => Promise<Response>;

  /**
   * Creates an instance of KernelApiClient.
   * @param options - Configuration options for client
   */
  constructor(options: KernelApiClientOptions = {}) {
    this.baseUrl = options.baseUrl || 'http://127.0.0.1:6806';
    this.apiToken = options.apiToken || '';
    this.customFetch = options.customFetch || (typeof fetch !== 'undefined' ? (...args)=> fetch(...args) : undefined as any);

    if (!this.customFetch) {
      throw new Error('Fetch API is not available. Please provide a customFetch implementation if running in an environment without fetch.');
    }
    if (this.baseUrl.endsWith('/')) {
        this.baseUrl = this.baseUrl.slice(0, -1);
    }
  }

  private async _fetchWrapper(endpoint: string, method: string, data?: any, needsAuth = false): Promise<any> {
    const url = \`\${this.baseUrl}\${endpoint}\`;
    const headers: Record<string, string> = {
      'User-Agent': 'KernelApiClient/1.0',
    };

    if (data && !(data instanceof FormData) && method !== 'GET' && method !== 'HEAD') {
        headers['Content-Type'] = 'application/json';
    }
    
    if (needsAuth && this.apiToken) {
      headers['Authorization'] = \`Token \${this.apiToken}\`;
    } else if (needsAuth && !this.apiToken && !this.baseUrl.startsWith('http://127.0.0.1')) {
      console.warn(\`API endpoint \${endpoint} requires authentication, but no API token was provided.\`);
    }

    const fetchOptions: RequestInit = {
      method,
      headers,
    };

    if (data !== undefined && method !== 'GET' && method !== 'HEAD') {
      if (data instanceof FormData) {
        fetchOptions.body = data;
      } else {
        fetchOptions.body = JSON.stringify(data);
      }
    } else if (data !== undefined && (method === 'GET' || method === 'HEAD')) {
      console.warn(\`Data payload for GET/HEAD request to \${endpoint} will be ignored by fetch. Consider moving data to query parameters if applicable.\`);
    }

    try {
      const response = await this.customFetch(url, fetchOptions);
      if (!response.ok) {
        let errorData;
        try {
          errorData = await response.json();
        } catch (e) {
          errorData = { message: response.statusText };
        }
        const error = new Error(\`\${method} \${endpoint} failed with status \${response.status}: \${errorData.message || response.statusText}\`);
        (error as any).status = response.status;
        (error as any).data = errorData;
        throw error;
      }

      if (response.status === 204) { // No Content
        return; 
      }
      
      let responseData;
      const contentType = response.headers.get('content-type');
      if (contentType && contentType.includes('application/json')) {
          responseData = await response.json();
      } else {
          responseData = await response.text(); // Or handle other content types as needed
      }
      
      // Assuming Siyuan API often wraps data in a top-level 'data' field
      // This might need to be more flexible based on actual API responses
      return responseData.data !== undefined ? responseData.data : responseData;

    } catch (error) {
      // If it's an error we threw deliberately from !response.ok, rethrow it
      if ((error as any).status) throw error; 
      // Otherwise, it's likely a network error or an issue with customFetch itself
      const networkError = new Error(\`Network error during \${method} \${endpoint}: \${(error as Error).message}\`);
      (networkError as any).cause = error;
      throw networkError;
    }
  }
`;

    apiDefs.forEach(apiDef => {
        const methodName = apiDef.en;
        if (!methodName) {
            console.warn(`API definition missing 'en' name, skipping:`, apiDef);
            return;
        }
        const methodSignatureTest = `async ${methodName}(`;
        if (classBody.includes(methodSignatureTest)) { // 基本检查重复项
            console.warn(`Duplicate method name '${methodName}' detected. Skipping subsequent definition from group '${apiDef.groupName}'. Check apiDef: ${apiDef.endpoint}`);
            return;
        }

        // 根据HTTP方法或是否定义了请求模式来确定方法是否需要数据参数
        const needsDataParam = (apiDef.method !== 'GET' && apiDef.method !== 'HEAD') || apiDef.zodRequestSchema;
        
        let paramType = 'any';
        if (needsDataParam && apiDef.zodRequestSchema) {
            try {
                let schema = apiDef.zodRequestSchema(z);
                if (isZodRawShape(schema)) {
                    schema = z.object(schema);
                }
                if (schema && schema._def) {
                    paramType = zodToTsType(schema);
                }
            } catch (e) {
                console.error(`Error parsing request schema for ${apiDef.en}:`, e);
            }
        }
        const params = needsDataParam ? `data: ${paramType}` : '';

        let returnType = 'any';
        if (apiDef.zodResponseSchema) {
            try {
                let schema = apiDef.zodResponseSchema(z);
                if (isZodRawShape(schema)) {
                    schema = z.object(schema);
                }
                if (schema && schema._def) {
                    returnType = zodToTsType(schema);
                }
            } catch (e) {
                console.error(`Error parsing response schema for ${apiDef.en}:`, e);
            }
        }
        const finalReturnType = returnType === 'void' ? 'Promise<void>' : `Promise<${returnType}>`;

        classBody += `\n${generateMethodTsDoc(apiDef, !!needsDataParam)}`;
        classBody += `  async ${methodName}(${params}): ${finalReturnType} {\n`;
        classBody += `    return this._fetchWrapper('${apiDef.endpoint}', '${apiDef.method}', ${needsDataParam ? 'data' : 'undefined'}, ${!!apiDef.needAuth});\n  }\n`;
        methodCount++; // 增加计数器
    });

    classBody += `
}

export default KernelApiClient;
export { KernelApiClientOptions };
`;

    try {
        fs.writeFileSync(OUTPUT_FILE, classBody);
        console.log(`Successfully generated TypeScript Kernel API client at: ${OUTPUT_FILE}`);
        console.log(`Total API methods generated: ${methodCount}`); // 记录数量

    } catch (error) {
        console.error(`Failed to write TypeScript Kernel API client: ${error}`);
    }
}

(async () => {
    await generateKernelApiClient();
})();