import { Constants } from "../../constants";
import { isElectron } from "../../platform";
import { ipcSend } from "../../platform/electron/ipcRenderer";
import { isBrowser } from "../platform/functions";
import { getSiyuanReqId, setSiyuanReqId } from "../siyuanEnvironments/getSiyuanConfig.environment";
import { getWindowJSAndroid, getWindowJSHarmony, getWindowWebkit } from "../siyuanEnvironments/windowNative.environment";
import { getServiceWorkerContainer, isServiceWorkerAvailable } from "../siyuanEnvironments/windowStandard.environment";
import { reloadLocation } from "../siyuanEnvironments/windowLocation.environment";

export { Constants };
export { isElectron };
export { ipcSend };
export { isBrowser };
export { getSiyuanReqId };
export { setSiyuanReqId };
export { getWindowJSAndroid };
export { getWindowJSHarmony };
export { getWindowWebkit };
export { getServiceWorkerContainer };
export { isServiceWorkerAvailable };
export { reloadLocation };
