/**
 * av (属性视图/数据库) 相关 API 定义
 *
 * 属性视图（数据库）操作相关的 API
 */
import { z } from 'zod';
import type { Api定义 } from '../client/types';
import { 创建响应Schema } from './types';

// ========== 通用 Schema 定义 ==========

/** 属性视图渲染结果 Schema */
const 属性视图渲染结果Schema = z.object({
    name: z.string().describe('属性视图的名称'),
    id: z.string().describe('属性视图的 ID'),
    viewType: z.any().describe('当前视图的类型'),
    viewID: z.any().describe('当前视图的 ID'),
    views: z.array(z.any()).describe('属性视图包含的所有视图定义数组'),
    view: z.any().describe('当前渲染的视图的详细数据'),
    isMirror: z.boolean().describe('是否为镜像属性视图'),
}).nullable();

/** 布局类型枚举 */
const 布局类型Schema = z.enum(['table', 'board', 'calendar', 'list', 'gallery']);

export const avApiDefs = [
    // ========== 渲染属性视图 ==========
    {
        method: 'POST',
        endpoint: '/api/av/renderAttributeView',
        en: 'renderAttributeView',
        zh_cn: '渲染属性视图',
        description: '渲染属性视图，获取其详细信息和视图数据。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('属性视图的 ID'),
            blockID: z.string().optional().describe('关联的块 ID'),
            viewID: z.string().optional().describe('可选，要渲染的特定视图的 ID'),
            query: z.string().optional().describe('可选，查询关键词或条件'),
            page: z.number().optional().describe('可选，页码'),
            pageSize: z.number().optional().describe('可选，每页数量'),
            groupPaging: z.record(z.any()).optional().describe('分组分页信息'),
        }),
        zodResponseSchema: 创建响应Schema(属性视图渲染结果Schema),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/renderHistoryAttributeView',
        en: 'renderHistoryAttributeView',
        zh_cn: '渲染历史版本属性视图',
        description: '渲染指定历史版本的属性视图。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('属性视图的 ID'),
            created: z.string().describe('历史版本创建的时间戳字符串'),
            blockID: z.string().optional().describe('关联的块 ID'),
            viewID: z.string().optional().describe('可选，要渲染的特定视图的 ID'),
            query: z.string().optional().describe('可选，查询关键词或条件'),
            page: z.number().optional().describe('可选，页码'),
            pageSize: z.number().optional().describe('可选，每页数量'),
            groupPaging: z.record(z.any()).optional().describe('分组分页信息'),
        }),
        zodResponseSchema: 创建响应Schema(属性视图渲染结果Schema),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/renderSnapshotAttributeView',
        en: 'renderSnapshotAttributeView',
        zh_cn: '渲染快照属性视图',
        description: '渲染指定快照索引的属性视图。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            snapshot: z.string().describe('快照的路径或标识'),
            id: z.string().describe('属性视图的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(属性视图渲染结果Schema),
        lastVerified: '2025-12-28',
    },

    // ========== 获取属性视图信息 ==========
    {
        method: 'POST',
        endpoint: '/api/av/getAttributeViewKeys',
        en: 'getAttributeViewKeys',
        zh_cn: '获取属性视图的列定义',
        description: '获取指定属性视图ID的所有列定义。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('属性视图的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.array(z.any()).nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/setAttributeViewBlockAttr',
        en: 'setAttributeViewBlockAttr',
        zh_cn: '设置属性视图块的单元格属性值',
        description: '更新属性视图中指定行、指定列的单元格的值。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            keyID: z.string().describe('列的 ID'),
            itemID: z.string().optional().describe('行的 ID (Item ID), 优先使用'),
            rowID: z.string().optional().describe('行的 ID (兼容旧版)'),
            value: z.any().describe('要设置的新值'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            value: z.any().describe('成功设置后的值'),
        }).nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/batchSetAttributeViewBlockAttrs',
        en: 'batchSetAttributeViewBlockAttrs',
        zh_cn: '批量设置属性视图块单元格值',
        description: '批量更新属性视图中多个单元格的值。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            values: z.array(z.object({
                blockID: z.string().describe('数据块的 ID'),
                keyID: z.string().describe('列的 ID'),
                value: z.any().describe('要设置的新值'),
            })).describe('包含多个要更新单元格信息的数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },

    // ========== 搜索属性视图 ==========
    {
        method: 'POST',
        endpoint: '/api/av/searchAttributeView',
        en: 'searchAttributeView',
        zh_cn: '搜索属性视图',
        description: '根据关键词搜索属性视图。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            keyword: z.string().describe('搜索关键词'),
            excludes: z.array(z.string()).optional().describe('要排除的属性视图 ID 数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            results: z.array(z.any()).describe('搜索结果对象数组'),
        }).nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/getAttributeView',
        en: 'getAttributeView',
        zh_cn: '获取属性视图',
        description: '获取指定ID的属性视图的详细信息。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            id: z.string().describe('属性视图的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            av: z.any().describe('属性视图对象的详细信息'),
        }).nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/searchAttributeViewRelationKey',
        en: 'searchAttributeViewRelationKey',
        zh_cn: '搜索属性视图的关联列',
        description: '根据关键词搜索指定属性视图的关联列。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            keyword: z.string().describe('搜索关键词'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            keys: z.array(z.any()).describe('匹配的关联列定义对象数组'),
        }).nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/searchAttributeViewNonRelationKey',
        en: 'searchAttributeViewNonRelationKey',
        zh_cn: '搜索属性视图的非关联列',
        description: '根据关键词搜索指定属性视图的非关联列。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            keyword: z.string().describe('搜索关键词'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            keys: z.array(z.any()).describe('匹配的非关联列定义对象数组'),
        }).nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/searchAttributeViewRollupDestKeys',
        en: 'searchAttributeViewRollupDestKeys',
        zh_cn: '搜索属性视图汇总目标列',
        description: '搜索属性视图汇总列的目标列。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            keyword: z.string().describe('搜索关键词'),
        }),
        zodResponseSchema: 创建响应Schema(z.any()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/getAttributeViewFilterSort',
        en: 'getAttributeViewFilterSort',
        zh_cn: '获取属性视图的筛选和排序规则',
        description: '获取指定属性视图的筛选条件和排序规则。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            id: z.string().describe('属性视图的 ID'),
            blockID: z.string().describe('属性视图关联的块 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            filters: z.array(z.any()).describe('筛选条件对象数组'),
            sorts: z.array(z.any()).describe('排序规则对象数组'),
        }).nullable()),
        lastVerified: '2025-12-28',
    },

    // ========== 列操作 ==========
    {
        method: 'POST',
        endpoint: '/api/av/addAttributeViewKey',
        en: 'addAttributeViewKey',
        zh_cn: '添加属性视图列',
        description: '向指定的属性视图添加一个新的列定义。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            keyID: z.string().describe('新列的 ID'),
            keyName: z.string().describe('新列的名称'),
            keyType: z.string().describe('新列的类型'),
            keyIcon: z.string().describe('新列的图标'),
            previousKeyID: z.string().describe('新列将插入到此列 ID 之前'),
        }),
        zodResponseSchema: 创建响应Schema(z.any().nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/removeAttributeViewKey',
        en: 'removeAttributeViewKey',
        zh_cn: '移除属性视图列',
        description: '从指定的属性视图移除一个列定义。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            keyID: z.string().describe('要移除的列的 ID'),
            removeRelationDest: z.boolean().optional().describe('如果是关联列，是否同时移除关联目标'),
        }),
        zodResponseSchema: 创建响应Schema(z.any().nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/sortAttributeViewViewKey',
        en: 'sortAttributeViewViewKey',
        zh_cn: '排序属性视图中特定视图的列',
        description: '对属性视图中某个特定视图的列进行排序。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            viewID: z.string().describe('特定视图的 ID'),
            keyID: z.string().describe('要移动的列的 ID'),
            previousKeyID: z.string().describe('目标位置：将列移动到此列 ID 之前'),
        }),
        zodResponseSchema: 创建响应Schema(z.any().nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/sortAttributeViewKey',
        en: 'sortAttributeViewKey',
        zh_cn: '排序属性视图列',
        description: '对属性视图的列进行排序。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            keyID: z.string().describe('要移动的列的 ID'),
            previousKeyID: z.string().describe('目标位置：将列移动到此列 ID 之前'),
        }),
        zodResponseSchema: 创建响应Schema(z.any().nullable()),
        lastVerified: '2025-12-28',
    },

    // ========== 块操作 ==========
    {
        method: 'POST',
        endpoint: '/api/av/addAttributeViewBlocks',
        en: 'addAttributeViewBlocks',
        zh_cn: '添加属性视图块',
        description: '向指定的属性视图中添加一个或多个数据块。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            blockID: z.string().optional().describe('新块将插入到此块 ID 之后'),
            viewID: z.string().optional().describe('视图 ID'),
            groupID: z.string().optional().describe('分组 ID'),
            previousID: z.string().optional().describe('新块将插入到此块 ID 之前'),
            ignoreDefaultFill: z.boolean().optional().describe('是否忽略默认填充'),
            srcs: z.array(z.record(z.any())).describe('要添加的源数据块信息数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.any().nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/removeAttributeViewBlocks',
        en: 'removeAttributeViewBlocks',
        zh_cn: '移除属性视图块',
        description: '从指定的属性视图中移除一个或多个数据块。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            srcIDs: z.array(z.string()).describe('要移除的源数据块的 ID 数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.any().nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/getAttributeViewPrimaryKeyValues',
        en: 'getAttributeViewPrimaryKeyValues',
        zh_cn: '获取属性视图主键列的值',
        description: '获取指定属性视图的主键列的值，支持分页和关键词搜索。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            id: z.string().describe('属性视图的 ID'),
            keyword: z.string().optional().describe('搜索关键词'),
            page: z.number().optional().describe('页码'),
            pageSize: z.number().optional().describe('每页数量'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            name: z.string().describe('主键列的名称'),
            blockIDs: z.array(z.string()).describe('匹配的主键值对应的块 ID 列表'),
            rows: z.array(z.any()).describe('匹配的行数据数组'),
        }).nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/setDatabaseBlockView',
        en: 'setDatabaseBlockView',
        zh_cn: '设置数据库块的默认视图',
        description: '设置指定数据库块的默认视图ID。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            id: z.string().describe('数据库块的 ID'),
            viewID: z.string().describe('要设置为默认视图的视图 ID'),
            avID: z.string().describe('属性视图的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.any().nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/getMirrorDatabaseBlocks',
        en: 'getMirrorDatabaseBlocks',
        zh_cn: '获取镜像数据库块',
        description: '获取指定属性视图ID的镜像数据库块ID列表。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            refDefs: z.array(z.object({
                refID: z.string().describe('引用的块ID'),
                defIDs: z.array(z.string()).describe('被引用的定义块ID列表'),
            })).describe('引用定义对象数组'),
        }).nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/getAttributeViewKeysByAvID',
        en: 'getAttributeViewKeysByAvID',
        zh_cn: '通过属性视图ID获取列定义',
        description: '通过属性视图ID获取其所有列定义。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.array(z.any()).nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/getAttributeViewKeysByID',
        en: 'getAttributeViewKeysByID',
        zh_cn: '通过ID获取属性视图列定义',
        description: '通过ID获取属性视图的列定义。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            keyIDs: z.array(z.string()).describe('列 ID 数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.any()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/duplicateAttributeViewBlock',
        en: 'duplicateAttributeViewBlock',
        zh_cn: '复制属性视图块',
        description: '复制一个属性视图块。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('要复制的属性视图块的 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            avID: z.string().describe('新复制的属性视图的 ID'),
            blockID: z.string().describe('新复制的属性视图块的 ID'),
        }).nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/appendAttributeViewDetachedBlocksWithValues',
        en: 'appendAttributeViewDetachedBlocksWithValues',
        zh_cn: '追加独立的属性视图块（带值）',
        description: '向属性视图追加多个新的独立块，并为这些块设置初始值。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            blocksValues: z.array(z.array(z.any())).describe('二维数组，外层代表多个新块，内层代表各列的初始值'),
        }),
        zodResponseSchema: 创建响应Schema(z.any().nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/getCurrentAttrViewImages',
        en: 'getCurrentAttrViewImages',
        zh_cn: '获取当前属性视图的图片',
        description: '获取当前属性视图中包含的所有图片资源。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('属性视图的 ID'),
            viewID: z.string().optional().describe('当前视图的 ID'),
            query: z.string().optional().describe('查询关键词'),
        }),
        zodResponseSchema: 创建响应Schema(z.array(z.string())),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/changeAttrViewLayout',
        en: 'changeAttrViewLayout',
        zh_cn: '改变属性视图布局',
        description: '改变指定属性视图的显示布局类型。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            blockID: z.string().describe('属性视图块的 ID'),
            avID: z.string().describe('属性视图的 ID'),
            layoutType: 布局类型Schema.describe('新的布局类型'),
        }),
        zodResponseSchema: 创建响应Schema(属性视图渲染结果Schema),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/setAttrViewGroup',
        en: 'setAttrViewGroup',
        zh_cn: '设置属性视图分组',
        description: '设置属性视图的块分组规则。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            blockID: z.string().describe('属性视图关联的块 ID'),
            group: z.any().describe('分组配置对象'),
        }),
        zodResponseSchema: 创建响应Schema(属性视图渲染结果Schema),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/batchReplaceAttributeViewBlocks',
        en: 'batchReplaceAttributeViewBlocks',
        zh_cn: '批量替换属性视图块',
        description: '批量替换属性视图中的现有块ID。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            isDetached: z.boolean().describe('是否处理独立的属性视图块'),
            oldNew: z.array(z.record(z.string(), z.string())).describe('包含旧块ID和新块ID映射关系的数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/getAttributeViewAddingBlockDefaultValues',
        en: 'getAttributeViewAddingBlockDefaultValues',
        zh_cn: '获取属性视图新增块默认值',
        description: '获取向属性视图添加块时的默认值。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            viewID: z.string().optional().describe('视图 ID'),
            groupID: z.string().optional().describe('分组 ID'),
            previousID: z.string().optional().describe('前一个块 ID'),
            addingBlockID: z.string().optional().describe('正在添加的块 ID'),
        }),
        zodResponseSchema: 创建响应Schema(z.any()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/av/getAttributeViewBoundBlockIDsByItemIDs',
        en: 'getAttributeViewBoundBlockIDsByItemIDs',
        zh_cn: '通过条目ID获取绑定的块ID',
        description: '通过属性视图条目ID获取绑定的块ID列表。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            itemIDs: z.array(z.string()).describe('条目 ID 数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.record(z.string(), z.string()).optional().describe('条目ID到块ID的映射')),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/av/getAttributeViewItemIDsByBoundIDs',
        en: 'getAttributeViewItemIDsByBoundIDs',
        zh_cn: '通过绑定ID获取属性视图条目ID',
        description: '通过绑定的块ID获取属性视图条目ID列表。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            avID: z.string().describe('属性视图的 ID'),
            blockIDs: z.array(z.string()).describe('块 ID 数组'),
        }),
        zodResponseSchema: 创建响应Schema(z.record(z.string(), z.string()).optional().describe('块ID到条目ID的映射')),
        lastVerified: '2025-12-29',
    },
] as const satisfies readonly Api定义[];

export type AvApiDefs = typeof avApiDefs;
