/**
 * 搜索相关 API 定义
 */
import { z } from 'zod';
import type { Api定义 } from '../client/types';
import { 创建响应Schema } from './types';

export const searchApiDefs = [
    {
        method: 'POST',
        endpoint: '/api/search/searchTag',
        en: 'searchTag',
        zh_cn: '搜索标签',
        description: '根据关键词搜索已存在的标签。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            k: z.string().describe('必需。搜索关键词。'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            tags: z.array(z.string()).describe('匹配到的标签列表。'),
            k: z.string().describe('原始搜索关键词。'),
        }).nullable()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/searchTemplate',
        en: 'searchTemplate',
        zh_cn: '搜索模板',
        description: '根据关键词搜索模板。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            k: z.string().describe('必需。搜索关键词。'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            blocks: z.array(z.object({
                content: z.string().describe('模板内容片段或文件名。'),
                path: z.string().describe('模板文件的相对路径。'),
                docpath: z.string().optional().describe('关联的文档路径。'),
            }).catchall(z.any())).describe('匹配到的模板列表。'),
            k: z.string().describe('原始搜索关键词。'),
        }).nullable()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/removeTemplate',
        en: 'removeTemplate',
        zh_cn: '移除模板',
        description: '根据路径移除指定的模板文件。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            path: z.string().describe('必需。要移除的模板文件的相对路径。'),
        }),
        zodResponseSchema: 创建响应Schema(z.null().describe('成功或失败时 Data 均为 null。')),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/searchWidget',
        en: 'searchWidget',
        zh_cn: '搜索挂件',
        description: '根据关键词搜索挂件块。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            k: z.string().describe('必需。搜索关键词。'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            blocks: z.array(z.object({
                id: z.string().describe('挂件块 ID。'),
                markdown: z.string().describe('挂件块的 Markdown 内容。'),
                name: z.string().describe('挂件块的名称。'),
            }).catchall(z.any())).describe('匹配到的挂件块列表。'),
            k: z.string().describe('原始搜索关键词。'),
        }).nullable()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/searchRefBlock',
        en: 'searchRefBlock',
        zh_cn: '搜索引用块建议',
        description: '在输入引用时，根据关键词动态搜索可能的引用块建议。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('必需。当前正在编辑的块的 ID。'),
            rootID: z.string().describe('必需。当前文档的根块 ID。'),
            k: z.string().describe('必需。用户输入的搜索关键词。'),
            beforeLen: z.number().int().optional().describe('可选。光标前字符长度。'),
            isSquareBrackets: z.boolean().optional().describe('可选。是否为双方括号引用 [[。'),
            isDatabase: z.boolean().optional().describe('可选。是否在数据库视图中搜索。'),
            reqId: z.any().optional().describe('可选。请求 ID。'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            blocks: z.array(z.object({
                id: z.string().describe('建议引用的块 ID。'),
                type: z.string().describe('块类型。'),
                content: z.string().describe('块内容预览或标题。'),
            }).catchall(z.any())).describe('引用建议块列表。'),
            newDoc: z.boolean().describe('是否建议创建一个新文档。'),
            k: z.string().describe('原始搜索关键词。'),
            reqId: z.any().optional().describe('透传的请求 ID。'),
        }).nullable()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/searchEmbedBlock',
        en: 'searchEmbedBlock',
        zh_cn: '搜索嵌入块内容 (SQL查询)',
        description: '在指定的嵌入块中使用 SQL 语句进行内容搜索。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            embedBlockID: z.string().describe('必需。作为搜索范围根的嵌入块 ID。'),
            stmt: z.string().describe('必需。用于搜索的 SQL 语句。'),
            excludeIDs: z.array(z.string()).optional().describe('可选。在搜索结果中排除的块 ID 数组。'),
            headingMode: z.number().int().min(0).optional().describe('可选。标题处理模式。'),
            breadcrumb: z.boolean().optional().describe('可选。是否显示面包屑路径。'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            blocks: z.array(z.any()).describe('满足 SQL 查询条件的块内容数组。'),
        }).nullable()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/getEmbedBlock',
        en: 'getEmbedBlock',
        zh_cn: '获取嵌入块内容',
        description: '获取指定嵌入块的渲染内容。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            embedBlockID: z.string().describe('必需。嵌入块的 ID。'),
            includeIDs: z.array(z.string()).describe('必需。要实际嵌入显示的块 ID 数组。'),
            headingMode: z.number().int().min(0).optional().describe('可选。标题处理模式。'),
            breadcrumb: z.boolean().optional().describe('可选。是否显示面包屑路径。'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            blocks: z.array(z.any()).describe('渲染后的嵌入块内容数组。'),
        }).nullable()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/updateEmbedBlock',
        en: 'updateEmbedBlock',
        zh_cn: '更新查询嵌入块内容',
        description: '更新指定查询嵌入块的原始查询语句或脚本内容。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('必需。要更新的查询嵌入块的 ID。'),
            content: z.string().describe('必需。查询嵌入块新的原始 Markdown 内容。'),
        }),
        zodResponseSchema: 创建响应Schema(z.null().describe('成功或失败时 Data 均为 null。')),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/fullTextSearchBlock',
        en: 'fullTextSearchBlock',
        zh_cn: '全文搜索块内容',
        description: '对块内容进行全文搜索，支持多种搜索方式和过滤条件。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            query: z.string().describe('必需。搜索查询语句。'),
            page: z.number().int().min(1).optional().describe('可选。页码，从 1 开始。'),
            pageSize: z.number().int().min(1).optional().describe('可选。每页数量。'),
            paths: z.array(z.string()).optional().describe('可选。限制查找范围的路径数组。'),
            boxes: z.array(z.string()).optional().describe('可选。限制查找范围的笔记本 ID 数组。'),
            types: z.record(z.boolean()).optional().describe('可选。指定要搜索的块类型。'),
            method: z.number().int().min(0).max(3).optional().describe('可选。搜索方法：0-关键字，1-查询语法，2-SQL，3-正则表达式。'),
            orderBy: z.number().int().min(0).max(7).optional().describe('可选。排序方式。'),
            groupBy: z.number().int().min(0).max(1).optional().describe('可选。分组方式。'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            blocks: z.array(z.any()).describe('当前页的搜索结果块列表。'),
            matchedBlockCount: z.number().int().describe('匹配到的块总数。'),
            matchedRootCount: z.number().int().describe('匹配到的根块总数。'),
            pageCount: z.number().int().describe('总页数。'),
            docMode: z.boolean().describe('是否为文档模式搜索结果。'),
        }).nullable()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/searchAsset',
        en: 'searchAsset',
        zh_cn: '搜索资源文件',
        description: '根据文件名关键词和可选的文件扩展名搜索资源文件。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            k: z.string().describe('必需。搜索关键词。'),
            exts: z.array(z.string()).optional().describe('可选。文件扩展名数组。'),
        }),
        zodResponseSchema: 创建响应Schema(z.array(z.object({
            id: z.string().describe('资源文件块 ID。'),
            box: z.string().describe('笔记本 ID。'),
            docID: z.string().describe('所属文档 ID。'),
            path: z.string().describe('资源文件路径。'),
            name: z.string().describe('资源文件名称。'),
            title: z.string().describe('文档标题。'),
            hPath: z.string().describe('文档层级路径。'),
            updated: z.string().describe('更新时间。'),
        })).describe('匹配到的资源文件列表。')),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/findReplace',
        en: 'findReplace',
        zh_cn: '查找并替换',
        description: '在指定的块ID范围、路径、笔记本、类型中查找内容并进行替换。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            k: z.string().describe('必需。要查找的关键词。'),
            r: z.string().describe('必需。要替换的字符串。'),
            ids: z.array(z.string()).describe('必需。要进行查找替换操作的块 ID 数组。'),
            paths: z.array(z.string()).optional().describe('可选。限制查找范围的路径数组。'),
            boxes: z.array(z.string()).optional().describe('可选。限制查找范围的笔记本 ID 数组。'),
            types: z.record(z.boolean()).optional().describe('可选。指定要搜索的块类型。'),
            method: z.number().int().min(0).max(3).optional().describe('可选。搜索方法。'),
            orderBy: z.number().int().min(0).max(7).optional().describe('可选。排序方式。'),
            groupBy: z.number().int().min(0).max(1).optional().describe('可选。分组方式。'),
            replaceTypes: z.record(z.boolean()).optional().describe('可选。指定替换时要处理的文本类型。'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            closeTimeout: z.number().optional().describe('对话框的关闭延迟时间（毫秒）。'),
        }).nullable()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/fullTextSearchAssetContent',
        en: 'fullTextSearchAssetContent',
        zh_cn: '全文搜索资源文件内容',
        description: '对资源文件内容进行全文搜索（此功能需要付费订阅）。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            query: z.string().describe('必需。搜索查询语句。'),
            page: z.number().int().min(1).optional().describe('可选。页码，从 1 开始。'),
            pageSize: z.number().int().min(1).optional().describe('可选。每页数量。'),
            types: z.record(z.boolean()).optional().describe('可选。指定要搜索的资源文件类型。'),
            method: z.number().int().min(0).max(3).optional().describe('可选。搜索方法。'),
            orderBy: z.number().int().min(0).max(3).optional().describe('可选。排序方式。'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            assetContents: z.array(z.object({
                id: z.string().describe('资源文件块 ID。'),
                box: z.string().describe('笔记本 ID。'),
                docID: z.string().describe('所属文档 ID。'),
                path: z.string().describe('资源文件路径。'),
                name: z.string().describe('资源文件名称。'),
                title: z.string().describe('文档标题。'),
                updated: z.string().describe('更新时间。'),
                content: z.string().describe('匹配到的内容片段。'),
                count: z.number().int().describe('匹配数量。'),
            })).describe('当前页的搜索结果列表。'),
            matchedAssetCount: z.number().int().describe('匹配到的资源文件总数。'),
            pageCount: z.number().int().describe('总页数。'),
        }).nullable()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/getAssetContent',
        en: 'getAssetContent',
        zh_cn: '获取资源文件指定内容片段',
        description: '获取资源文件内容中，与指定查询相关的片段。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            id: z.string().describe('必需。资源文件块的 ID。'),
            query: z.string().describe('必需。查询关键词。'),
            queryMethod: z.number().int().min(0).max(3).describe('必需。查询方法。'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            assetContent: z.string().describe('匹配到的资源文件内容片段。'),
        }).nullable()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/search/listInvalidBlockRefs',
        en: 'listInvalidBlockRefs',
        zh_cn: '列出无效的块引用',
        description: '分页列出在当前工作空间中所有无效的块引用。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            page: z.number().int().min(1).optional().describe('可选。页码。'),
            pageSize: z.number().int().min(1).optional().describe('可选。每页数量。'),
        }),
        zodResponseSchema: 创建响应Schema(z.object({
            blocks: z.array(z.object({
                id: z.string().describe('包含无效引用的块的 ID。'),
                box: z.string().describe('笔记本 ID。'),
                path: z.string().describe('文档路径。'),
                hPath: z.string().describe('文档层级路径。'),
                content: z.string().describe('块内容预览。'),
                updated: z.string().describe('块更新时间。'),
            })).describe('当前页的无效引用块列表。'),
            matchedBlockCount: z.number().int().describe('匹配到的无效引用块总数。'),
            matchedRootCount: z.number().int().describe('匹配到的包含无效引用的文档总数。'),
            pageCount: z.number().int().describe('总页数。'),
        }).nullable()),
        lastVerified: '2025-12-29',
    },
] as const satisfies readonly Api定义[];

export type SearchApiDefs = typeof searchApiDefs;
