/**
 * 存储相关 API 定义
 */
import { z } from 'zod';
import type { Api定义 } from '../client/types';
import { 创建响应Schema } from './types';

// ====== 复用的 Schema ======

/** 搜索标准 Schema */
const 搜索标准Schema = z.object({
    name: z.string().describe('搜索标准的唯一名称。'),
    id: z.string().optional().describe('搜索标准的ID。'),
    box: z.string().optional().describe('笔记本 ID。'),
    type: z.string().optional().describe('类型，例如 "doc", "asset" 等。'),
    query: z.string().optional().describe('搜索关键词或 SQL 查询语句。'),
    sort: z.number().optional().describe('排序方式。'),
    group: z.number().optional().describe('分组方式。'),
    types: z.any().optional().describe('类型筛选条件。'),
    customSort: z.array(z.any()).optional().describe('自定义排序规则。'),
    filter: z.number().optional().describe('过滤条件。'),
    docIDs: z.array(z.string()).optional().describe('文档 ID 列表。'),
    blockIDs: z.array(z.string()).optional().describe('块 ID 列表。'),
    tagIDs: z.array(z.string()).optional().describe('标签 ID 列表。'),
    attrIDs: z.array(z.string()).optional().describe('属性 ID 列表。'),
    refs: z.array(z.string()).optional().describe('引用 ID 列表。'),
    parentID: z.string().optional().describe('父块 ID。'),
    rootID: z.string().optional().describe('根块 ID。'),
    kwd: z.string().optional().describe('关键词。'),
});

export const storageApiDefs = [
    {
        method: 'POST',
        endpoint: '/api/storage/setLocalStorage',
        en: 'setLocalStorage',
        zh_cn: '整体设置本地存储',
        description: '使用一个完整的对象来覆盖整个浏览器 LocalStorage 的内容。通常用于导入或恢复 LocalStorage 数据。同时会广播事件通知其他客户端同步设置。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            val: z.record(z.any()).describe('一个对象，其键值对将完全替换现有的 LocalStorage 内容。'),
            app: z.string().describe('发起操作的 App ID，用于事件广播。'),
        }),
        zodResponseSchema: 创建响应Schema(z.null().describe('接口成功执行时，Data 固定为 null。')),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/getLocalStorage',
        en: 'getLocalStorage',
        zh_cn: '获取所有本地存储项',
        description: '获取浏览器 LocalStorage 中的所有键值对。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}).optional(),
        zodResponseSchema: 创建响应Schema(z.record(z.any()).describe('包含 LocalStorage 所有键值对的对象。')),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/setLocalStorageVal',
        en: 'setLocalStorageVal',
        zh_cn: '设置单个本地存储项',
        description: '设置浏览器 LocalStorage 中的单个键值对。同时会广播事件通知其他客户端同步设置。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            key: z.string().describe('要设置的 LocalStorage 项目的键名。'),
            val: z.any().describe('要设置的 LocalStorage 项目的值。'),
            app: z.string().describe('发起操作的 App ID，用于事件广播。'),
        }),
        zodResponseSchema: 创建响应Schema(z.null().describe('接口成功执行时，Data 固定为 null。')),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/removeLocalStorageVals',
        en: 'removeLocalStorageVals',
        zh_cn: '批量移除本地存储项',
        description: '根据提供的键名列表，批量移除浏览器 LocalStorage 中的项目。同时会广播事件通知其他客户端同步移除。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            keys: z.array(z.string()).describe('要移除的 LocalStorage 项目的键名数组。'),
            app: z.string().describe('发起操作的 App ID，用于事件广播。'),
        }),
        zodResponseSchema: 创建响应Schema(z.null().describe('接口成功执行时，Data 固定为 null。')),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/setCriterion',
        en: 'setCriterion',
        zh_cn: '保存搜索标准',
        description: '保存或更新一个搜索标准（过滤条件）。搜索标准可用于后续的文档或内容搜索。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            criterion: 搜索标准Schema.describe('要保存或更新的搜索标准对象。'),
        }),
        zodResponseSchema: 创建响应Schema(z.null().describe('接口成功执行时，Data 固定为 null。')),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/getCriteria',
        en: 'getCriteria',
        zh_cn: '获取所有已保存的搜索标准',
        description: '获取所有用户已保存的搜索标准（过滤条件）列表。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}).optional(),
        zodResponseSchema: 创建响应Schema(z.array(搜索标准Schema).describe('已保存的搜索标准列表。')),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/removeCriterion',
        en: 'removeCriterion',
        zh_cn: '移除搜索标准',
        description: '根据名称移除一个已保存的搜索标准（过滤条件）。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            name: z.string().describe('要移除的搜索标准的名称。'),
        }),
        zodResponseSchema: 创建响应Schema(z.null().describe('接口成功执行时，Data 固定为 null。')),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/getRecentDocs',
        en: 'getRecentDocs',
        zh_cn: '获取最近打开的文档列表',
        description: '获取用户最近打开过的文档列表。这些文档按最近打开时间排序。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}).optional(),
        zodResponseSchema: 创建响应Schema(z.array(z.object({
            id: z.string().describe('文档的 ID。'),
            notebookID: z.string().describe('文档所属笔记本的 ID。'),
            name: z.string().describe('文档的名称。'),
            icon: z.string().describe('文档的图标。'),
            hPath: z.string().describe('文档的人类可读路径。'),
            path: z.string().describe('文档的存储路径。'),
            sort: z.number().describe('文档的排序值。'),
            type: z.string().describe('文档的类型。'),
            subFileCount: z.number().describe('子文件数量。'),
            updated: z.string().describe('文档的最后更新时间。'),
        })).describe('最近打开的文档列表。')),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/updateRecentDocViewTime',
        en: 'updateRecentDocViewTime',
        zh_cn: '更新最近文档查看时间',
        description: '更新指定文档的最近查看时间。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}).optional(),
        zodResponseSchema: 创建响应Schema(z.object({}).optional()),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/updateRecentDocCloseTime',
        en: 'updateRecentDocCloseTime',
        zh_cn: '更新最近文档关闭时间',
        description: '更新指定文档的最近关闭时间。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}).optional(),
        zodResponseSchema: 创建响应Schema(z.object({}).optional()),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/updateRecentDocOpenTime',
        en: 'updateRecentDocOpenTime',
        zh_cn: '更新最近文档打开时间',
        description: '更新指定文档的最近打开时间。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}).optional(),
        zodResponseSchema: 创建响应Schema(z.object({}).optional()),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/getOutlineStorage',
        en: 'getOutlineStorage',
        zh_cn: '获取大纲存储',
        description: '获取大纲存储数据。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}).optional(),
        zodResponseSchema: 创建响应Schema(z.object({}).optional()),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/setOutlineStorage',
        en: 'setOutlineStorage',
        zh_cn: '设置大纲存储',
        description: '设置大纲存储数据。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({}).optional(),
        zodResponseSchema: 创建响应Schema(z.object({}).optional()),
    },
    {
        method: 'POST',
        endpoint: '/api/storage/removeOutlineStorage',
        en: 'removeOutlineStorage',
        zh_cn: '移除大纲存储',
        description: '移除大纲存储数据。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({}).optional(),
        zodResponseSchema: 创建响应Schema(z.object({}).optional()),
    },
] as const satisfies readonly Api定义[];

export type StorageApiDefs = typeof storageApiDefs;
