/**
 * 系统相关 API 定义
 */
import { z } from 'zod';
import type { Api定义 } from '../client/types';
import { 创建响应Schema } from './types';

/**
 * 启动进度 Schema
 */
const BootProgressSchema = z.object({
    progress: z.number().describe('启动进度百分比'),
    details: z.string().describe('当前启动状态的详细描述'),
});

/**
 * 工作空间信息 Schema
 */
const WorkspaceSchema = z.object({
    path: z.string().describe('工作空间的绝对路径'),
    name: z.string().optional().describe('工作空间的名称'),
    title: z.string().optional().describe('工作空间的标题'),
    bookmark: z.string().optional().describe('工作空间的备注/书签'),
    closed: z.boolean().describe('工作空间是否已关闭'),
});

/**
 * 系统字体 Schema
 */
const SysFontSchema = z.object({
    label: z.string().describe('字体名称，用于显示'),
    value: z.string().describe('字体族名称，用于 CSS'),
});

/**
 * 网络代理配置 Schema
 */
const NetworkProxySchema = z.object({
    scheme: z.string().describe('代理协议，如 http, socks5'),
    host: z.string().describe('代理服务器地址'),
    port: z.string().describe('代理端口'),
});

/**
 * Emoji 配置 Schema
 */
const EmojiItemSchema = z.object({
    unicode: z.string().describe('Emoji 的 Unicode 表示或自定义 Emoji 的文件名'),
    description: z.string().describe('Emoji 描述'),
    description_zh_cn: z.string().optional(),
    description_ja_jp: z.string().optional(),
    keywords: z.string().optional().describe('搜索关键词'),
});

const EmojiGroupSchema = z.object({
    id: z.string().describe('Emoji 分组 ID'),
    title: z.string().describe('分组标题'),
    title_zh_cn: z.string().optional(),
    title_ja_jp: z.string().optional(),
    items: z.array(EmojiItemSchema).describe('Emoji 项列表'),
});

export const systemApiDefs = [
    // === 无需认证的 API ===
    {
        method: 'GET',
        endpoint: '/api/system/bootProgress',
        en: 'bootProgress',
        zh_cn: '获取启动进度',
        description: '获取思源笔记内核的启动进度。此接口也接受 POST 请求。',
        needAuth: false,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(BootProgressSchema.nullable()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/bootProgress',
        en: 'bootProgress',
        zh_cn: '获取启动进度 (POST)',
        description: '获取思源笔记内核的启动进度。此接口也接受 GET 请求。',
        needAuth: false,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(BootProgressSchema.nullable()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'GET',
        endpoint: '/api/system/version',
        en: 'version',
        zh_cn: '获取版本号',
        description: '获取当前思源笔记内核的版本号。此接口也接受 POST 请求。',
        needAuth: false,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.string().describe('版本号字符串')),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/version',
        en: 'version',
        zh_cn: '获取版本号 (POST)',
        description: '获取当前思源笔记内核的版本号。此接口也接受 GET 请求。',
        needAuth: false,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.string().describe('版本号字符串')),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/currentTime',
        en: 'currentTime',
        zh_cn: '获取当前服务器时间',
        description: '获取思源笔记服务器当前的 Unix 时间戳 (毫秒)。',
        needAuth: false,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.number().describe('Unix 时间戳 (毫秒)')),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/uiproc',
        en: 'addUIProcess',
        zh_cn: '添加 UI 进程信息',
        description: '（内部接口）用于桌面端添加 UI 进程的相关信息。',
        needAuth: false,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            pid: z.number().int().optional().describe('UI 进程的 PID'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/loginAuth',
        en: 'LoginAuth',
        zh_cn: '登录授权',
        description: '使用访问授权码进行登录验证。',
        needAuth: false,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            authcode: z.string().optional().describe('访问授权码'),
            captcha: z.string().optional().describe('验证码'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/logoutAuth',
        en: 'LogoutAuth',
        zh_cn: '退出登录',
        description: '清除当前的登录授权状态。',
        needAuth: false,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'GET',
        endpoint: '/api/system/getCaptcha',
        en: 'GetCaptcha',
        zh_cn: '获取验证码',
        description: '获取用于登录验证的图片验证码。返回的是图片二进制数据。',
        needAuth: false,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: z.any().describe('图片二进制数据'),
        lastVerified: '2025-12-29',
    },

    // === 需要认证但非管理员权限的 API ===
    {
        method: 'POST',
        endpoint: '/api/system/getEmojiConf',
        en: 'getEmojiConf',
        zh_cn: '获取 Emoji 配置',
        description: '获取内置及自定义 Emoji 的配置信息。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.array(EmojiGroupSchema)),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/getWorkspaces',
        en: 'getWorkspaces',
        zh_cn: '获取所有工作空间列表',
        description: '获取所有已配置或曾经打开过的工作空间列表。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.array(WorkspaceSchema)),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/getConf',
        en: 'getConf',
        zh_cn: '获取所有配置',
        description: '获取思源笔记的全部配置信息。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(
            z.object({
                conf: z.any().describe('完整配置对象'),
                start: z.boolean().describe('UI 是否已加载'),
                isPublish: z.boolean().describe('是否发布模式'),
            })
        ),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/getChangelog',
        en: 'getChangelog',
        zh_cn: '获取更新日志',
        description: '获取当前版本的更新日志内容。',
        needAuth: true,
        needAdminRole: false,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(
            z.object({
                show: z.boolean().describe('是否需要显示更新日志'),
                html: z.string().describe('更新日志的 HTML 内容'),
            })
        ),
        lastVerified: '2025-12-28',
    },

    // === 需要管理员权限的 API ===
    {
        method: 'POST',
        endpoint: '/api/system/setAPIToken',
        en: 'setAPIToken',
        zh_cn: '设置 API 令牌',
        description: '设置或清空 API 访问令牌。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            token: z.string().describe('新的 API 令牌，空字符串表示清空'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/setAccessAuthCode',
        en: 'setAccessAuthCode',
        zh_cn: '设置访问授权码',
        description: '设置或清空访问思源笔记的授权码。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            accessAuthCode: z.string().describe('新的授权码，空字符串表示清空'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/setFollowSystemLockScreen',
        en: 'setFollowSystemLockScreen',
        zh_cn: '设置跟随系统锁屏',
        description: '设置是否在系统锁屏时自动锁定。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            lockScreenMode: z.number().int().describe('锁屏模式: 0=跟随系统, 1=手动, 2=禁用'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/setNetworkServe',
        en: 'setNetworkServe',
        zh_cn: '设置网络服务',
        description: '配置思源笔记的网络服务。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            networkServe: z.boolean().describe('是否允许远程访问'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/setAutoLaunch',
        en: 'setAutoLaunch',
        zh_cn: '设置开机自启动',
        description: '设置是否开机自启动（仅桌面端）。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            autoLaunch: z.number().int().describe('开机自启动模式: 0=禁用, 1=启用, 2=后台启动'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/setDownloadInstallPkg',
        en: 'setDownloadInstallPkg',
        zh_cn: '设置自动下载更新包',
        description: '设置是否自动下载并安装更新包。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            downloadInstallPkg: z.boolean().describe('是否自动下载更新包'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/setNetworkProxy',
        en: 'setNetworkProxy',
        zh_cn: '设置网络代理',
        description: '设置网络代理服务器。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            scheme: z.string().describe('代理协议，如 http, socks5'),
            host: z.string().describe('代理服务器地址'),
            port: z.string().describe('代理端口'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/setWorkspaceDir',
        en: 'setWorkspaceDir',
        zh_cn: '设置当前工作空间',
        description: '切换到指定路径的工作空间。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            path: z.string().describe('工作空间绝对路径'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/getMobileWorkspaces',
        en: 'getMobileWorkspaces',
        zh_cn: '获取移动端工作空间列表',
        description: '获取用于移动端同步的工作空间列表。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.array(z.string()).describe('工作空间路径列表')),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/checkWorkspaceDir',
        en: 'checkWorkspaceDir',
        zh_cn: '检查工作空间目录',
        description: '检查指定路径是否可以作为工作空间。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            path: z.string().describe('要检查的目录路径'),
        }),
        zodResponseSchema: 创建响应Schema(
            z.object({
                isWorkspace: z.boolean().describe('是否可以作为工作空间'),
            }).nullable()
        ),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/createWorkspaceDir',
        en: 'createWorkspaceDir',
        zh_cn: '创建工作空间目录',
        description: '在指定路径创建新的工作空间。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            path: z.string().describe('工作空间目录路径'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/removeWorkspaceDir',
        en: 'removeWorkspaceDir',
        zh_cn: '移除工作空间',
        description: '从工作空间列表中移除指定目录（逻辑删除）。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            path: z.string().describe('工作空间绝对路径'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/removeWorkspaceDirPhysically',
        en: 'removeWorkspaceDirPhysically',
        zh_cn: '物理删除工作空间',
        description: '从工作空间列表中移除并物理删除指定目录。危险操作！',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            path: z.string().describe('要删除的工作空间路径'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/setAppearanceMode',
        en: 'setAppearanceMode',
        zh_cn: '设置外观模式',
        description: '设置外观模式（亮色/暗色）。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            mode: z.number().int().min(0).max(1).describe('0=亮色，1=暗色'),
        }),
        zodResponseSchema: 创建响应Schema(
            z.object({
                appearance: z.any().describe('更新后的外观配置对象'),
            })
        ),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/setUILayout',
        en: 'setUILayout',
        zh_cn: '设置 UI 布局',
        description: '设置用户界面的布局模式。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({
            layout: z.any().describe('UI 布局配置对象'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/getSysFonts',
        en: 'getSysFonts',
        zh_cn: '获取系统字体列表',
        description: '获取当前系统上可用的字体列表。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.array(SysFontSchema)),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/exit',
        en: 'exit',
        zh_cn: '退出程序',
        description: '关闭并退出思源笔记程序。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            force: z.boolean().optional().describe('是否强制退出，忽略同步状态'),
            execInstallPkg: z.number().int().optional().describe('0=默认检查新版本, 1=不执行安装, 2=执行安装'),
            setCurrentWorkspace: z.boolean().optional().describe('是否设置当前工作空间'),
        }),
        zodResponseSchema: 创建响应Schema(
            z.object({
                closeTimeout: z.number().optional().describe('关闭超时时间'),
            }).nullable()
        ),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/checkUpdate',
        en: 'checkUpdate',
        zh_cn: '检查更新',
        description: '检查是否有新版本。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({
            showMsg: z.boolean().describe('是否显示提示消息'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/exportLog',
        en: 'exportLog',
        zh_cn: '导出日志',
        description: '导出系统运行日志的压缩文件。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(
            z.object({
                zip: z.string().describe('日志压缩文件的绝对路径'),
            })
        ),
        lastVerified: '2025-12-29',
    },
    {
        method: 'POST',
        endpoint: '/api/system/getNetwork',
        en: 'getNetwork',
        zh_cn: '获取网络配置',
        description: '获取当前的网络代理等配置。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(
            z.object({
                proxy: NetworkProxySchema.describe('代理服务器配置'),
            })
        ),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/exportConf',
        en: 'exportConf',
        zh_cn: '导出配置',
        description: '导出当前用户所有配置。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: false,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(
            z.object({
                name: z.string().describe('配置文件名'),
                zip: z.string().describe('压缩文件的相对路径'),
            })
        ),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/importConf',
        en: 'importConf',
        zh_cn: '导入配置',
        description: '通过上传 conf.json 导入配置。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        formDataRequest: true,
        zodRequestSchema: z.object({
            file: z.any().describe('conf.json 文件'),
        }),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/getWorkspaceInfo',
        en: 'getWorkspaceInfo',
        zh_cn: '获取当前工作空间信息',
        description: '获取当前工作空间路径和思源版本号。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(
            z.object({
                workspaceDir: z.string().describe('工作空间路径'),
                siyuanVer: z.string().describe('思源版本号'),
            })
        ),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/reloadUI',
        en: 'reloadUI',
        zh_cn: '重新加载 UI',
        description: '命令客户端重新加载用户界面。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/addMicrosoftDefenderExclusion',
        en: 'addMicrosoftDefenderExclusion',
        zh_cn: '添加 Microsoft Defender 排除项',
        description: '将思源相关目录添加到 Windows Defender 排除项。仅 Windows 有效。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/ignoreAddMicrosoftDefenderExclusion',
        en: 'ignoreAddMicrosoftDefenderExclusion',
        zh_cn: '忽略添加 Defender 排除项提示',
        description: '设置不再提示用户添加 Defender 排除项。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/vacuumDataIndex',
        en: 'vacuumDataIndex',
        zh_cn: '清理数据索引',
        description: '清理和压缩数据索引。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
    {
        method: 'POST',
        endpoint: '/api/system/rebuildDataIndex',
        en: 'rebuildDataIndex',
        zh_cn: '重建数据索引',
        description: '重建全部数据索引。',
        needAuth: true,
        needAdminRole: true,
        unavailableIfReadonly: true,
        zodRequestSchema: z.object({}),
        zodResponseSchema: 创建响应Schema(z.null()),
        lastVerified: '2025-12-28',
    },
] as const satisfies readonly Api定义[];

export type SystemApiDefs = typeof systemApiDefs;
