// Auto-generated by dynamic_tool. Editable.
export default {
  description: "Debug ESLint comment locations for a file",
  args: {
  "filePath": {
    "type": "string",
    "description": "File path"
  }
},
  execute: async (args, ctx) => {
    const { filePath } = args;
    const { Linter } = require("eslint");
    const linter = new Linter();
    
    // Read the file
    const fs = require("fs");
    const sourceCode = fs.readFileSync(filePath, "utf-8");
    
    // Parse with typescript parser
    const tsParser = require("@typescript-eslint/parser");
    const ast = tsParser.parse(sourceCode, {
        ecmaVersion: "latest",
        sourceType: "module",
        jsx: true,
    });
    
    // Get all comments
    const comments = ast.comments || [];
    const result = [];
    
    for (const comment of comments) {
        result.push({
            type: comment.type,
            value: comment.value,
            loc: comment.loc,
            range: comment.range,
        });
    }
    
    // Also find class declarations and their positions
    function findClasses(node, depth = 0) {
        let classes = [];
        if (!node || typeof node !== 'object') return classes;
        
        if (node.type === 'ClassDeclaration' || node.type === 'ClassExpression') {
            classes.push({
                type: node.type,
                name: node.id?.name || '(anonymous)',
                loc: node.loc,
                abstract: node.abstract || false,
                superClass: !!node.superClass,
            });
        }
        
        if (node.type === 'ExportNamedDeclaration' && node.declaration) {
            const childClasses = findClasses(node.declaration, depth + 1);
            classes.push({
                parentType: node.type,
                parentLoc: node.loc,
                childClasses: childClasses,
            });
        }
        
        for (const key of Object.keys(node)) {
            if (key === 'parent') continue;
            if (Array.isArray(node[key])) {
                for (const item of node[key]) {
                    classes = classes.concat(findClasses(item, depth + 1));
                }
            } else if (typeof node[key] === 'object' && node[key] !== null) {
                classes = classes.concat(findClasses(node[key], depth + 1));
            }
        }
        
        return classes;
    }
    
    const classes = findClasses(ast);
    
    return JSON.stringify({ comments, classes }, null, 2);
  },
}
