// Auto-generated by dynamic_tool. Editable.
export default {
  description: "读取文件指定行并返回原始内容",
  args: {
  "filePath": {
    "type": "string",
    "description": "文件路径"
  },
  "startLine": {
    "type": "number",
    "description": "起始行号（从1开始）"
  },
  "endLine": {
    "type": "number",
    "description": "结束行号（含）"
  }
},
  execute: async (args, ctx) => {
    const { filePath, startLine, endLine } = args;
    const content = await Bun.file(filePath).text();
    const lines = content.split("\n");
    const result = [];
    for (let i = startLine - 1; i < Math.min(endLine, lines.length); i++) {
        const lineNum = i + 1;
        const line = lines[i];
        result.push({
            line: lineNum,
            hex: Array.from(new TextEncoder().encode(line)).map(b => b.toString(16).padStart(2, "0")).join(" "),
            content: line
        });
    }
    return JSON.stringify(result, null, 2);
  },
}
